// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWhmSP9Hm6BbsSNnltjgkazKxEhvfjJRg',
    appId: '1:260669652586:web:5f74f29c24782fd7be1413',
    messagingSenderId: '260669652586',
    projectId: 'studentpal-1129c',
    authDomain: 'studentpal-1129c.firebaseapp.com',
    storageBucket: 'studentpal-1129c.firebasestorage.app',
    measurementId: 'G-7TE3DJKBLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcizi1LfCQKFN3ZJQyBmDxLf2a7pQf6i8',
    appId: '1:260669652586:android:24c3c19f9e6aa84bbe1413',
    messagingSenderId: '260669652586',
    projectId: 'studentpal-1129c',
    storageBucket: 'studentpal-1129c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvY0zgBTz_6xfcI4xs0Bk1maZ3s9yoeV0',
    appId: '1:260669652586:ios:4c541c26ef690fc0be1413',
    messagingSenderId: '260669652586',
    projectId: 'studentpal-1129c',
    storageBucket: 'studentpal-1129c.firebasestorage.app',
    iosBundleId: 'com.example.studentPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvY0zgBTz_6xfcI4xs0Bk1maZ3s9yoeV0',
    appId: '1:260669652586:ios:4c541c26ef690fc0be1413',
    messagingSenderId: '260669652586',
    projectId: 'studentpal-1129c',
    storageBucket: 'studentpal-1129c.firebasestorage.app',
    iosBundleId: 'com.example.studentPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWhmSP9Hm6BbsSNnltjgkazKxEhvfjJRg',
    appId: '1:260669652586:web:46528c7eac4a2895be1413',
    messagingSenderId: '260669652586',
    projectId: 'studentpal-1129c',
    authDomain: 'studentpal-1129c.firebaseapp.com',
    storageBucket: 'studentpal-1129c.firebasestorage.app',
    measurementId: 'G-1LZQ0SRJWN',
  );
}
